### PR TITLE
Fix #219: Hold Exception

### LINKED ISSUE #219: Illuminate\Database\QueryException in PUT /hold/assigned
## Error in UK Controller Plugin API

**Illuminate\Database\QueryException** in **PUT /hold/assigned**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'EZY409R' for key 'network_aircraft.PRIMARY' (SQL: insert into `network_aircraft` (`callsign`, `updated_at`, `transponder_last_updated_at`, `created_at`) values (EZY409R, 2020-08-01 16:10:08, 2020-08-01 16:10:08, 2020-08-01 16:10:08))

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f2593e14562260017665784?event_id=5f2593e1005b69ab6d120000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/HoldController.php:172 - App\Http\Controllers\HoldController::assignHold
    app/Http/Middleware/UserIsDisabled.php:42 - App\Http\Middleware\UserIsDisabled::handle
    app/Http/Middleware/UserIsBanned.php:43 - App\Http\Middleware\UserIsBanned::handle
    app/Http/Middleware/Authenticate.php:73 - App\Http\Middleware\Authenticate::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f2593e14562260017665784?event_id=5f2593e1005b69ab6d120000&i=gh&m=ci)

*Created by Andy Ford via Bugsnag*

### PR DESCRIPTION
**Pull request by AndyTWF**

### CODE REVIEW

File: app/Http/Controllers/HoldController.php [hunk 1]
```diff
@@ -169,11 +170,14 @@ public function assignHold(Request $request): JsonResponse
...
-        $networkAircraft = NetworkAircraft::firstOrCreate(['callsign' => $request->json('callsign')]);
+        NetworkDataService::firstOrCreateNetworkAircraft(
+            $request->json('callsign'),
+            ['callsign' => $request->json('callsign')]
+        );
         $assignedHold = AssignedHold::updateOrCreate(
             ['callsign' => $request->json('callsign')],
             [
-                'callsign' => $networkAircraft->callsign,
+                'callsign' => $request->json('callsign'),
```
Comment (atoff) [inline app/Http/Controllers/HoldController.php:180]: Would it be better to assign the model creation to a variable and then do `->callsign` like before - I am thinking this might minimise repetition / required changes if we end up changing in the input name? Either that or assign `$callsign = $request->json('callsign')` and reference that everywhere?

Comment (AndyTWF) [reply app/Http/Controllers/HoldController.php]: Done!
