### PR TITLE
fix(networkdata): handle invalid transponder from datafeed

### LINKED ISSUE #553: Illuminate\Database\QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'code' at row 1 (SQL...
Sentry Issue: [UKCP-API-5](https://sentry.io/organizations/vatsim-uk/issues/2453316993/?referrer=github_integration)

```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'code' at row 1
  File "/app/Services/SquawkService.php", line 199, in App\Services\SquawkService::reserveActiveSquawks
    'assignment_type' => 'NON_UKCP',
  File "/app/Jobs/Squawk/ReserveActiveSquawks.php", line 16, in App\Jobs\Squawk\ReserveActiveSquawks::handle
    $squawkService->reserveActiveSquawks();
  File "/artisan", line 35
    exit($kernel->handle(new ArgvInput, new ConsoleOutput));
...
(48 additional frame(s) were not displayed)

Illuminate\Database\QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'code' at row 1 (SQL: insert into `squawk_assignments` (`callsign`, `code`, `assignment_type`, `created_at`) values (ACH7192, 16665, NON_UKCP, 2021-06-13 13:25:04))
  File "/app/Services/SquawkService.php", line 199, in App\Services\SquawkService::reserveActiveSquawks
    'assignment_type' => 'NON_UKCP',
  File "/app/Jobs/Squawk/ReserveActiveSquawks.php", line 16, in App\Jobs\Squawk\ReserveActiveSquawks::handle
    $squawkService->reserveActiveSquawks();
  File "/artisan", line 35
    exit($kernel->handle(new ArgvInput, new ConsoleOutput));
...
(46 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by AndyTWF**
Sometimes we get an insane squawk code from the datafeed, so ignore any data containing this

fix #553

### CODE REVIEW

File: app/Services/NetworkDataService.php [hunk 1]
```diff
@@ -204,4 +205,9 @@ public static function firstOrCreateNetworkAircraft(
 
         return $aircraft;
     }
+
+    private function pilotValid(array $pilot): bool
+    {
+        return preg_match('/^[0-7]{4}$/', $pilot['transponder']);
```
Comment (AxonC) [inline app/Services/NetworkDataService.php:211]: Assuming you're keeping `0000` as a valid transponder code?

**Review by AxonC — APPROVED** [review]

File: app/Services/NetworkDataService.php (hunk 1 above)
Comment (AxonC) [reply app/Services/NetworkDataService.php:211]: (I know it is one, but I think (?) FSD uses 0000 as some invalid indicator?)

Comment (AndyTWF) [reply app/Services/NetworkDataService.php:211]: Yeah - it technically is valid, though also not!
