### PR TITLE
128 fix config cache

### LINKED ISSUE #17: Don't use env() other then in config files and use artisan config:cache for speed boost
In some files the `env()` helper is used.

This is only allowed to be used in `config/*` files due to the fact that when utilizing `php artisan config:cache` upon deployment it will give the application a speed boost but restrict the usage of `env()` in the rest of the code.

In the current state, adding the `config:cache` command will break the application.

Ref: https://laravel.com/docs/5.7/configuration#retrieving-environment-configuration
` However, you may use the env helper to retrieve values from these variables in your configuration files`

Ref: https://laravel.com/docs/5.7/configuration#configuration-caching
`If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files`

Therefore I would do two things:

- Extract the usage of `env()` to newly created configuration files and use the `config()` helper instead
- Enable `config:cache` during deployment to make use of the speed boost

I'm willing to pick this up if you like.

### LINKED ISSUE #128: Fix Config Caching
- Config caching is breaking prod.

### PR DESCRIPTION
**Pull request by AndyTWF**
Close #128 
Close #17

### CODE REVIEW

File: config/metar.php [hunk 1]
```diff
@@ -0,0 +1,7 @@
+<?php
+
+// Config for downloading METARs in the context of MSL and RPS
+return [
+    'vatsim_url' => env('VATSIM_METAR_URL', 'metar.vatsim.net'),
+    'regional_url' => env('APP_REGIONAL_PRESSURES_URL'),
```
Comment (AxonC) [inline config/metar.php:6]: Would it be sensible to provide a default?

Comment (AndyTWF) [reply config/metar.php]: Done!
