### PR TITLE
Prevent squawk integrity violations

### LINKED ISSUE #198: Primary Key Exception In Squawk Assignments
## Error in UK Controller Plugin API

**Illuminate\Database\QueryException** in **PUT /squawk-assignment/BEE6AF**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7536' for key 'ccams_squawk_assignments.ccams_squawk_assignments' (SQL: insert into `ccams_squawk_assignments` (`callsign`, `code`, `created_at`) values (BEE6AF, 7536, 2020-07-22 10:25:49))

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f16e412972dce00179a62be?event_id=5f18142d005b73fa48920000&i=gh&m=ci)

## Stacktrace

    app/Allocator/Squawk/General/CcamsSquawkAllocator.php:36 - App\Allocator\Squawk\General\CcamsSquawkAllocator::App\Allocator\Squawk\General\{closure}
    app/Allocator/Squawk/General/CcamsSquawkAllocator.php:40 - App\Allocator\Squawk\General\CcamsSquawkAllocator::allocate
    app/Services/SquawkService.php:117 - App\Services\SquawkService::App\Services\{closure}
    app/Services/SquawkService.php:122 - App\Services\SquawkService::assignSquawk
    app/Services/SquawkService.php:105 - App\Services\SquawkService::assignGeneralSquawk
    app/Http/Controllers/SquawkController.php:127 - App\Http\Controllers\SquawkController::assignGeneralSquawk
    app/Http/Controllers/SquawkController.php:98 - App\Http\Controllers\SquawkController::assignSquawk
    app/Http/Middleware/UserIsDisabled.php:42 - App\Http\Middleware\UserIsDisabled::handle
    app/Http/Middleware/UserIsBanned.php:43 - App\Http\Middleware\UserIsBanned::handle
    app/Http/Middleware/Authenticate.php:73 - App\Http\Middleware\Authenticate::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f16e412972dce00179a62be?event_id=5f18142d005b73fa48920000&i=gh&m=ci)

*Created by Calum Towers via Bugsnag*

### PR DESCRIPTION
**Pull request by AndyTWF**
Fix #198 

- Stops squawk integrity violations from happening by locking the ranges during an insert.
- Registers missing events for audit purposes.

### CODE REVIEW

File: app/Allocator/Squawk/General/AirfieldPairingSquawkAllocator.php [hunk 1]
```diff
@@ -23,41 +23,60 @@ private function getPossibleRangesForFlight(string $origin, string $destination)
...
         }
 
         $assignment = null;
-        $this->getPossibleRangesForFlight($details['origin'], $details['destination'])->each(
-            function (AirfieldPairingSquawkRange $range) use (&$assignment, $callsign) {
-                $allSquawks = $range->getAllSquawksInRange();
-                $possibleSquawks = $allSquawks->diff(
-                    AirfieldPairingSquawkAssignment::whereIn('code', $allSquawks)->pluck('code')->all()
-                );
+        AirfieldPairingSquawkRange::getConnectionResolver()->connection()->transaction(
```
Comment (atoff) [inline app/Allocator/Squawk/General/AirfieldPairingSquawkAllocator.php:42]: Out of curiosity, is there a reason this syntax is used instead of a generic DB transaction? i.e. like https://laravel.com/docs/7.x/database#database-transactions

If they do the same thing, it might make it a bit more readable? Could even use `DB::beginTransaction();` to eliminate the need for the closure and passing in the required variables

Comment (AndyTWF) [reply app/Allocator/Squawk/General/AirfieldPairingSquawkAllocator.php]: Changed!
