### PR TITLE
Fix #199: Network Data Downtime

### LINKED ISSUE #199: Handle Network Data Downtime
## Error in UK Controller Plugin API

**GuzzleHttp\Exception\ServerException** in **artisan networkdata:update**
Server error: `GET http://cluster.data.vatsim.net/vatsim-data.json` resulted in a `502 Bad Gateway` response:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>clou (truncated...)

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f0bce5c0d36b90017071111?event_id=5f1214eb005b811a03c90000&i=gh&m=ci)

## Stacktrace

    Services/NetworkDataService.php:27 - App\Services\NetworkDataService::updateNetworkData
    Console/Commands/UpdateVatsimNetworkData.php:43 - App\Console\Commands\UpdateVatsimNetworkData::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f0bce5c0d36b90017071111?event_id=5f1214eb005b811a03c90000&i=gh&m=ci)

*Created by Calum Towers via Bugsnag*

### PR DESCRIPTION
**Pull request by AndyTWF**

### CODE REVIEW

File: app/Services/NetworkDataService.php [hunk 1]
```diff
@@ -26,7 +27,12 @@ public function __construct(Client $client)
 
     public function updateNetworkData(): void
     {
-        $data = json_decode($this->client->get(self::NETWORK_DATA_URL)->getBody(), true);
+        try {
+            $data = json_decode($this->client->get(self::NETWORK_DATA_URL)->getBody(), true);
```
Comment (atoff) [inline app/Services/NetworkDataService.php:31]: Would recommend you consider the HTTP facade - the graceful 400+ error handling should work well in this context without having to try catch https://laravel.com/docs/7.x/http-client

File: app/Services/NetworkDataService.php [hunk 2]
```diff
@@ -6,28 +6,23 @@
...
     {
-        $data = json_decode($this->client->get(self::NETWORK_DATA_URL)->getBody(), true);
-        $this->processClients($data['clients']);
+        $networkResponse = Http::get(self::NETWORK_DATA_URL);
+        if (!$networkResponse->successful()) {
+            Log::warning('Failed to download network data, response was ' . $networkResponse->status());
+            return;
+        }
+
+        $this->processClients(json_decode($networkResponse->body(), true)['clients']);
```
Comment (atoff) [inline app/Services/NetworkDataService.php:25]:
```suggestion
        $this->processClients($networkResponse->json()['clients']);
```

Comment (AndyTWF) [reply app/Services/NetworkDataService.php:25]: Done!
